### ISSUE TITLE
Release DLLs?

### ISSUE THREAD

**Issue by RUSshy** [texus/TGUI.Net#1]
Hello

Im complete noob, i tried to compile sfml csfml etc but i failed, i'm too stupid xD, where could i find ready dlls ?

Ty!

**Comment by texus** [comment]
TGUI.Net is still in a relatively early phase of development. Although practically all the code is there, it hasn't been fully tested and I haven't had the time yet to really create a guide on how to install it. Currently there aren't any compiled libraries.

I have some time now, I could have a look if I can manage to build them for you. Could you answer the following questions so that I know which library to build exactly?
- Which compiler you are using? VS2013 or VS2015?
- Do you want to use 32 or 64 bit sfml libraries?
- Are you going to use Debug or Release mode?

**Comment by RUSshy** [comment]
I am free to test it and give feedback :D

I am using visual studio 2017, i'm not really good in c++ stuff, i compile all my projects with AnyCPU so x86 or x64 don't matter, but x64  Release is fine for me :)

**Comment by texus** [comment]
Hmm, I can't build for VS2017 because I don't have it installed. I was waiting for it to be fully released first.

As far as I know you can't use AnyCPU because this library is a binding and will have to link with either the 32-bit or 64-bit C library.

**Comment by RUSshy** [comment]
Ok i will install vs 2015, but for c# it doesn't matter the version of visual studio i think

**Comment by texus** [comment]
Yeah, maybe it would work. I don't know how much the C and C++ code will influence that, because in C++ the version will matter. It indeed shouldn't matter, you should test and find out once you have the libraries.

**Comment by RUSshy** [comment]
Ok i got vs2015 installed, it took a while compared to vs2017 xD

**Comment by texus** [comment]
I'm still figuring out how to build the .net libs, at least I already have the C libraries ready.

**Comment by RUSshy** [comment]
I already have SFML.NET and TGUI.NET the missing thing is CSFML and CTGUI i failed with these C thing :/

**Comment by texus** [comment]
You can't use the official SFML.Net version since it is out of date, the c++ TGUI 0.8-dev library requires at least SFML 2.4 which complicate things a bit. Once SFML.Net 2.4 gets released I would only need to compile all tgui libs, now I have to do the sfml libs as well.

I think I stumbled onto an error in ctgui though. I have all libraries now but I can't use them in my test project yet :)
Plus I noticed that CTGUI will always give a warning that it can't find CSFML even when it finds it.
It's pretty obvious that this hasn't really been tested on windows before :D

**Comment by texus** [comment]
I've made some fixes to ctgui and tgui.net and I now have 64-bit libraries.

You can download it here: https://www.dropbox.com/s/pxurtha8illsalz/TGUI.Net%200.8-dev%202017-02-02.zip?dl=1

You should check if your widgets display text though, the text seemed to be corrupted here. I'm not sure yet why.

**Comment by RUSshy** [comment]
Thanks a lot, i'll test that :D

**Comment by RUSshy** [comment]
Is it SFML 2.4 or 2.3 ?

**Comment by texus** [comment]
It is SFML 2.4.1.
All the files you need should be in the zip file though, you shouldn't need to download anything else.

**Comment by RUSshy** [comment]
Hmm i get an error 

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ctgui-0.8': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I put ctgui right next to my exe

**Comment by texus** [comment]
That would mean that I send you a wrong file. Just try renaming ctgui-0.8.dll to ctgui-0.8 for now, that should work if it is located right next to your exe.

**Comment by RUSshy** [comment]
Yes removing .dll works lol, but weird think now is the font looks weird http://i.imgur.com/eTuSdTL.png

**Comment by texus** [comment]
Ok, so that is definately a but in TGUI.Net then and not just a problem on my pc. I'll look into it.

**Comment by RUSshy** [comment]
Ok thanks :) also the background picture isn't rendered

**Comment by texus** [comment]
There is something seriously broken, probably memory corruption somewhere.

**Comment by RUSshy** [comment]
:/ sounds like it is something hard to catch

**Comment by texus** [comment]
Yeah, I have no idea how to find this issue. And a bigger problem is that if I don't find it fast I won't have much time to look for it anymore.
I'm going to compile an example code with CTGUI now, hopefully the problem already exists there. But if it only happens in C# then I really don't know what to do.

For c++ I know which tools to use to debug these kind of issues, but right now I'm working in a language that I hardly know, on an OS that I dislike and using development tools that I almost never use.

There is of course one possible cause that I know of: the sfml libraries are not completely compatible. TGUI requires SFML 2.4 but SFML.Net 2.4 does not exist yet. So I'm using the latest SFML.Net which may not be 100% compatible. If this is indeed the issue (which I can't verify) then the only thing we can do is wait for SFML to update their CSFML and SFML.Net version.

On linux the code works fine but it crashes on exit if I don't manually clean the memory. I've always ignored this because the sfml libraries weren't compatible and I assumed that that would be the cause. These memory issues might of course be related to the bigger issues that we are seeing on windows.

**Comment by RUSshy** [comment]
I noticed something, if i load the texture for the background, but don't use it, then the Picture widget correctly render it

**Comment by texus** [comment]
I never got tgui to draw anything but depending on which things I did during initialization, sfml rendering either worked or was broken. So the problem is definately not related to a small piece of code.

It apparently already happens in CTGUI, so I don't have to focus on TGUI.Net anymore.

**Comment by RUSshy** [comment]
Oh ok i'll stop check in the C# code too then and try to remenber C to try help you to find the issue 😄

**Comment by texus** [comment]
I don't think C is going to help much with this. The C binding is really a bit of black magic, it is actually written in c++, it just has a C API :)

**Comment by texus** [comment]
I'm giving up for now.

The code works perfectly fine on linux without valgrind giving me any errors (usually when something works only on linux and not on other platforms I get tons of memory errors). The only reason that I have seen in the past for things working on linux and not working on windows are the use of uninitialized memory, which is why I keep suspecting that this is the case again.

I can't find any obvious flaw so maybe we should just wait for CSFML 2.4 to be released, then we can exclude the possibility of incompatible libraries. It would be frustrating to spend a lot of time debugging now only to figure out that that was the problem all along.

**Comment by RUSshy** [comment]
Oh ok :( they are so slow to update csfml and sfml.net, i think ill make my own ui but i too lazy xD

But ty for your time and for helping me!

**Comment by texus** [comment]
The more I looked into it the less I suspect that it is a problem with SFML though. Rendering text with CSFML works so I must have some bug in the CTGUI libraries.

The behavior that I'm seeing just doesn't make sense.
- Whenever I add a widget to the gui I get tons of "Failed to create texture, invalid size (0x0)" errors indicating that the internal font isn't being set correctly.
- When I create a picture and set a texture, nothing gets renderered anymore, not even sfml stuff.

**Comment by RUSshy** [comment]
I wish i could help but c++ and c is out of my knowledge :(, but yes i can render text and image fine with SFML.NET so issue might come from CTGUI, have you tested with TGUI on windows ?

**Comment by texus** [comment]
Yeah, I tested the c++ TGUI library on windows yesterday and it worked fine. The libs that I used are the exact same libraries that I am linking CTGUI with so the problem must be related to the C binding.

I finally managed to get TGUI, CTGUI and my example code in one project so that I don't have copy dlls around the whole time to debug and I found some minimal code to reproduce the issues. If CTGUI calls a function in TGUI which allocates a sf::Texture object, then everything from that moment is broken. I have no idea why, but all opengl calls start failing from that point. Even when the texture is immediately destroyed, just allocating (and executing its default constructor) is enough to break everything.

**Comment by RUSshy** [comment]
https://github.com/texus/CTGUI/blob/master/src/CTGUI/Widgets/Picture.cpp#L43

https://github.com/texus/TGUI/blob/master/src/TGUI/Widgets/Picture.cpp#L73

in TGUI setTexture requiere 2 params

But in CTGUI you only pass 1 param, is that enough to create the issue?, i don't know how default value works in c/c++ but in C# it'd refuse to compile

**Comment by texus** [comment]
In c++ you set the default parameter in the header. If you look at the declaration of the function you will see that the second parameter has a default value.

But you won't be able to find it based on looking at the code, that is why I have been repeating that it works fine on linux. If it were a logical error in the code then it wouldn't work there either.

I figured out that just creating an sf::Texture object in CTGUI is already enough.

I have a new theory for the bug. What if the c++ TGUI libraries link statically to the SFML libraries. The CSFML libs do the same thing. When linking them together in CTGUI, there are 2 identical versions. Only the one from CSFML gets fully initialized and when calling code in TGUI it uses the wrong uninitialized SFML code and therefore fails. I can at least come up with one reason why what I just wrote is nonsense, but it might be worth trying to link dynamically instead of statically. In the end, on linux I am also linking dynamically (as that is the way you typically work on linux).

**Comment by texus** [comment]
Everything works when linking dynamically, so so you will just have to put the c++ sfml and tgui dlls next to your executable as well.
I'll package all needed files and send them to you in a moment.

I'm pretty angry at windows right now. When I first tried to link dynamically I was getting BadImageFormatException errors. I tried rebuilding my libraries a couple of time but nothing worked. It turned out that the dll was really broken, I couldn't even open it in Dependency Walker. Rebuilding it didn't solve the problem. Eventually I completely removed the CTGUI build folder, setup the same thing again and now the dll was build correctly. So VS had been producing corrupted dlls for the last hour. Static libraries still don't work so this isn't the reason for the earlier issues.

**Comment by texus** [comment]
Apparently there is still one more issue in the code: it crashes when you close the window. Since I can reproduce this with only SFML code and since it fails in a part that I know has changed between SFML 2.2 and 2.4 I'm going to assume that this is an incompatibility and ignore this for now. When SFML.Net 2.4 gets released I'll rebuild the libraries and hopefully it will be solved then.

You can download the TGUI.Net binaries at https://www.dropbox.com/s/106qk5tjj13s4kb/TGUI.Net%200.8-dev%202017-02-03.zip?dl=1

**Comment by RUSshy** [comment]
It works fine :D thanks a lot :D :D :D

http://i.imgur.com/WulvPTc.png

And when i close the window it doesn't crash for me

**Comment by RUSshy** [comment]
For the moment 0 issue to be reported :) it is a great lib, so clean, and so easy to customize controls, i love it

**Comment by texus** [comment]
Thanks. I'm glad you like it.
At least I have 1 user for this library now :)

**Comment by RUSshy** [comment]
Oh i found one issue, if i click on a button that execute some code, then it crash

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TGUI.Gui.tguiGui_handleEvent(IntPtr cPointer, Event ev)
   at TGUI.Gui.HandleEvent(Event ev) in C:\Users\texus\Downloads\TGUI.Net-master\src\Gui.cs:line 284
   at TGUI.Gui.OnMouseReleased(Object sender, MouseButtonEventArgs e) in C:\Users\texus\Downloads\TGUI.Net-master\src\Gui.cs:line 212

And this is weird cause it gives your path xD

**Comment by texus** [comment]
My example code where I print something when a button gets clicked works fine so I can't reproduce the issue.

Could you find out what it is exactly you need to do to get that error and send me the code so I can reproduce it here?

**Comment by RUSshy** [comment]
https://gist.github.com/RUSshy/5d3f8c9aa8e324e932801247fdf4ff10

With this small example you can reproduce it

if you click multiple time on the button it'll crash

**Comment by texus** [comment]
It doesn't crash here

**Comment by RUSshy** [comment]
if i spam click it crash for me :/ http://imgur.com/a/b7rN5

**Comment by RUSshy** [comment]
in my project (not that test one) it crash at the 2nd click

**Comment by texus** [comment]
Ok, it finally crashed here too. But I had to click it more than 20x very rapidly.

**Comment by RUSshy** [comment]
If i catch the exception, ignore it and continue to click, then i get this crash:

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Still at the same place:    at TGUI.Gui.tguiGui_handleEvent(IntPtr cPointer, Event ev)

**Comment by texus** [comment]
I think I already figured out what the problem is. It is indeed likely using memory that is already released. I'm currently testing my solution.

**Comment by texus** [comment]
The good news is that I figured out what the issue is and that I found a solution.
The bad news is that it takes a lot of work to implement the solution.

The following diff has to be applied to TGUI.Net to fix just your issue. You should be able to build TGUI.Net yourself as it only has CTGUI as a dependency on runtime.

A similar fix however has to be made for every other widget for every callback.
```
diff --git a/src/Widget.cs b/src/Widget.cs
index 39af01d..a5f9faf 100644
--- a/src/Widget.cs
+++ b/src/Widget.cs
@@ -265,19 +265,23 @@ namespace TGUI
 		{
 			IntPtr error;
 
-			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("PositionChanged"), ProcessPositionChangedSignal, out error);
+			PositionChangedCallback = new CallbackActionVector2f(ProcessPositionChangedSignal);
+			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("PositionChanged"), PositionChangedCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 
-			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("SizeChanged"), ProcessSizeChangedSignal, out error);
+			SizeChangedCallback = new CallbackActionVector2f(ProcessSizeChangedSignal);
+			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("SizeChanged"), SizeChangedCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 
-			tguiWidget_connect(CPointer, Util.ConvertStringForC_ASCII("MouseEntered"), ProcessMouseEnteredSignal, out error);
+			MouseEnteredCallback = new CallbackAction(ProcessMouseEnteredSignal);
+			tguiWidget_connect(CPointer, Util.ConvertStringForC_ASCII("MouseEntered"), MouseEnteredCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 
-			tguiWidget_connect(CPointer, Util.ConvertStringForC_ASCII("MouseLeft"), ProcessMouseLeftSignal, out error);
+			MouseLeftCallback = new CallbackAction(ProcessMouseLeftSignal);
+			tguiWidget_connect(CPointer, Util.ConvertStringForC_ASCII("MouseLeft"), MouseLeftCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 		}
@@ -319,6 +323,12 @@ namespace TGUI
 		public event EventHandler MouseLeft = null;
 
 
+		private CallbackActionVector2f PositionChangedCallback;
+		private CallbackActionVector2f SizeChangedCallback;
+		private CallbackAction         MouseEnteredCallback;
+		private CallbackAction         MouseLeftCallback;
+
+
 		protected Dictionary<string, List<uint>> myConnectedSignals = new Dictionary<string, List<uint>>();
 
 
@@ -431,4 +441,4 @@ namespace TGUI
 
 		#endregion
 	}
-}
\ No newline at end of file
+}
diff --git a/src/Widgets/Button.cs b/src/Widgets/Button.cs
index 3cd906f..e33d1b1 100644
--- a/src/Widgets/Button.cs
+++ b/src/Widgets/Button.cs
@@ -70,7 +70,8 @@ namespace TGUI
 			base.InitSignals();
 
 			IntPtr error;
-			tguiWidget_connect_string(CPointer, Util.ConvertStringForC_ASCII("Pressed"), ProcessPressedSignal, out error);
+			PressedCallback = new CallbackActionString(ProcessPressedSignal);
+			tguiWidget_connect_string(CPointer, Util.ConvertStringForC_ASCII("Pressed"), PressedCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 		}
@@ -84,6 +85,7 @@ namespace TGUI
 		/// <summary>Event handler for the Pressed signal</summary>
 		public event EventHandler<SignalArgsString> Pressed = null;
 
+		private CallbackActionString PressedCallback;
 
 		#region Imports
 
diff --git a/src/Widgets/ClickableWidget.cs b/src/Widgets/ClickableWidget.cs
index 8a191c5..588e327 100644
--- a/src/Widgets/ClickableWidget.cs
+++ b/src/Widgets/ClickableWidget.cs
@@ -63,15 +63,18 @@ namespace TGUI
 			base.InitSignals();
 			IntPtr error;
 
-			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("MousePressed"), ProcessMousePressedSignal, out error);
+			MousePressedCallback = new CallbackActionVector2f(ProcessMousePressedSignal);
+			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("MousePressed"), MousePressedCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 
-			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("MouseReleased"), ProcessMouseReleasedSignal, out error);
+			MouseReleasedCallback = new CallbackActionVector2f(ProcessMouseReleasedSignal);
+			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("MouseReleased"), MouseReleasedCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 
-			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("Clicked"), ProcessClickedSignal, out error);
+			ClickedCallback = new CallbackActionVector2f(ProcessClickedSignal);
+			tguiWidget_connect_vector2f(CPointer, Util.ConvertStringForC_ASCII("Clicked"), ClickedCallback, out error);
 			if (error != IntPtr.Zero)
 				throw new TGUIException(Util.GetStringFromC_ASCII(error));
 		}
@@ -103,6 +106,9 @@ namespace TGUI
 		/// <summary>Event handler for the Clicked signal</summary>
 		public event EventHandler<SignalArgsVector2f> Clicked = null;
 
+		private CallbackActionVector2f MousePressedCallback;
+		private CallbackActionVector2f MouseReleasedCallback;
+		private CallbackActionVector2f ClickedCallback;
 
 		#region Imports
 
```

**Comment by RUSshy** [comment]
It fixed it thanks :D, i'll do it for u and send PR

**Comment by texus** [comment]
Thanks, that would be great.

**Comment by RUSshy** [comment]
Ok done, but i think i talked too fast, it is fixed for the example above, but for my project it still crash, i don't know what i did, ill test again

**Comment by texus** [comment]
Don't you have extra information when it crashes? When it crashed for me I always got some error like "A callback was made on a garbage collected delegate of type ..." from which I could figure out which delegate was the problem.

Try removing some widgets, if you have a widget in which you missed one callback then just creating this widget and moving your mouse can cause the crash.

**Comment by RUSshy** [comment]
I never had this messsage, only a NullPointerException :/, i'll continue to test

**Comment by RUSshy** [comment]
Here is full stack trace, i have only  1 Grid 2 EditBox and 1 Button 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TGUI.Gui.tguiGui_handleEvent(IntPtr cPointer, Event ev)
   at TGUI.Gui.HandleEvent(Event ev) in C:\Users\ruuu\Projects\ProjectRPG\TGUI.Net\src\Gui.cs:line 284
   at TGUI.Gui.OnMousePressed(Object sender, MouseButtonEventArgs e) in C:\Users\ruuu\Projects\ProjectRPG\TGUI.Net\src\Gui.cs:line 192
   at SFML.Window.Window.CallEventHandler(Event e) in C:\Users\ruuu\Projects\ProjectRPG\SFML.Net\src\Window\Window.cs:line 556
   at SFML.Window.Window.DispatchEvents() in C:\Users\ruuu\Projects\ProjectRPG\SFML.Net\src\Window\Window.cs:line 367
   at Game.Core..ctor() in C:\Users\ruuu\Projects\ProjectRPG\Game\Program.cs:line 53
   at Game.Program.Main(String[] args) in C:\Users\ruuu\Projects\ProjectRPG\Game\Program.cs:line 16
```

**Comment by RUSshy** [comment]
I counted, no need to spam click, it'll crash at the 12th click

**Comment by texus** [comment]
Maybe this is a different error, does it happen with the code from earlier or do I need a different example to test it here?

Btw, could you also adapt the following in your pull request:
- In SpinButton.cs the parameter to tguiWidget_connect_int is still ProcessValueChangedSignal instead of ValueChangedCallback.
- There were 5 lines where you added ".dll" in the DllImport. Could you also remove the space behind DllImport in these lines so that these lines will not remain unchanged again when I do a 'replace all'?

**Comment by RUSshy** [comment]
Here is the class from my project

https://gist.github.com/RUSshy/8b8cb53c40526f8d303853f8cea92b95

**Comment by RUSshy** [comment]
I fixed the PR

**Comment by texus** [comment]
I can't reproduce it. No matter how much I click it, it doesn't crash.
Are you certain you aren't still using the previous version? Because the old dll was called tgui-0.8.dll while the new one is called tguinet-0.8.dll
If you are certain that you are using the one from your callbacks branch then maybe you should try to create a minimal code so that we are testing with identical code (as I'm currently testing with something based on that class you send but this is not identical to the code that you execute).

**Comment by RUSshy** [comment]
Yes i rechecked everything multiple times and it still crash :(

I created a test repo: 

https://github.com/RUSshy/Test

**Comment by RUSshy** [comment]
Oh and i was using Rider, i just tried with VS2017 and i get a different error:

```
Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'tguinet-0.8!TGUI.Widget+CallbackActionVector2f::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'
```

**Comment by texus** [comment]
That is the error that I got in VS2015 before your callbacks update.
I'm going to check the test repo now.

**Comment by RUSshy** [comment]
I'll try with VS2015 too

**Comment by texus** [comment]
Ok, I'm getting the error with that code.
Why does c# need that damn garbage collector, can't it just be like c++ where a value is either initialized or uninitialized instead of being initialized until the pc finally decided to free it.

**Comment by texus** [comment]
It seems to be related to the VerticalLayout. Just a button in the gui is fine, but a button inside a layout inside the gui seems to crash.

**Comment by RUSshy** [comment]
Oh nice catch! indeed if i add button alone, no crash, only if i add to a vlayout xD

**Comment by RUSshy** [comment]
It also happens if the button is added to a Grid              root.AddWidget(btnLogin,0,0);

**Comment by texus** [comment]
I haven't tested it yet, but I think I know what the problem is. I was looking at the wrong place, it is not related to the fact that button has a parent other than the gui at all.
The button is the only object that is stored outside that function, the other widgets (including the VerticalLayout) get destroyed after the TestState() function has done executing.
When a callback arrives, the object no longer exists. Keeping a reference to every widget in your code should solve this.

**Comment by RUSshy** [comment]
Again you are right, keepring reference of all widgets solve the issue  :) thanks a lot!

But this will be a problem no? im not sure if i can keep reference for every widget i'll create, like items in a table view

It'll be easier to do this:

public void Refresh()
{
table.Clear();
var vLayout = new Vlayout();
var characterIcon = new Icon();
var characterName = new Labe();
var characterBtnSelect = new Btn();
characterBtnSelect.Click += () => ..

vLayout.add(..) 
(..))

table.add(vLayout);
}

Do you think you can fix it, or it is how it is supposed to be used ?

**Comment by texus** [comment]
It will be fixed (I'm working on it now). I will store all widgets that you add to the container in the container itself so that, just like in c++, you don't have to manually store the widget.

**Comment by RUSshy** [comment]
You are awesome thanks :D

Also one design question about TGUI, shouldn't it be better if let the user handle the events instead of internally hooking the input events, so i can do check if input is for UI or for Gameplay for example ?

Because for the moment i cant figure out how to do check and separate ui input with gameplay

And one last question, how do you  set focus / un focus / check focus of a widget like an EditBox?

**Comment by texus** [comment]
Widgets are now stored and won't get garbage collected anymore as long as they are added to the gui or container.

Feel free to suggest an alternative for the input. I don't want to force the user to do things in order to receive inputs, the fact that it happens automatically is one of the things that makes the library easy to use. But I'm open for suggestions on how to implement it in a way that it remains easy for beginners and also allows you to take control over it when you need to.

Certain parts of the library where not implemented in .Net for different reasons. I believe that I left out focussing because I keep telling myself that I will rewrite it at some point in 0.8-dev and it would be added then. But I'm not sure if that part will ever get rewritten. I will have to update CTGUI in order to add support for it though.

**Comment by RUSshy** [comment]
Thanks a lot, focus is the only missing thing i needed :D

For the input, i'll try to experiment stuff and send a pull request so you'll be able to see how it looks like
